# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
