# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171019_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
